services:
  app:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: .env
    depends_on:
      - db_sql
      - db_nosql
      - db_vector

  db_sql:
    image: postgres:16
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "${SQL_PORT}:5432"


  db_nosql:
    image: mongo:latest
    ports:
      - "27017:27017"  # expose so you can run api_ingestion from host with MONGO_HOST=localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  db_vector:
    image: chromadb/chroma:latest
    environment:
      - CHROMA_DB_PATH=${VECTOR_DB_PATH}
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "${VECTOR_PORT}:8000"

volumes:
  postgres_data:
  mongo_data:
  chroma_data: